### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cvegagimenez** [rhythmictech/terraform-aws-nlb-ecs-task#5]
**Describe the bug**
When trying to create a a Target Group with TCP protocol, the module tries to use the _stickiness_ block and results in an incompatibility error.

**To Reproduce**
1. Use the example to create a TCP Target Group.
```
module "example" {
  source = "github.com/rhythmictech/terraform-aws-nlb-ecs-task?ref=master"

  cluster_name                 = var.cluster_name
  container_port               = var.port
  container_image              = var.image
  load_balancer_arn            = var.load_balancer
  listener_port                = var.port
  name                         = var.name
  subnets                      = var.subnet_id
  tags                         = var.tags
  vpc_id                       = var.vpc_id
}
```
2. Run the apply command.
```
terraform apply
```
3. Check error
```
╷
│ Error: error modifying Target Group Attributes: InvalidConfigurationRequest: Stickiness type 'lb_cookie' is not supported for target groups with the TCP protocol
│ 	status code: 400, request id: 99ed0e5f-d635-4952-9308-3baedf5d9c1a
│ 
│   with aws_lb_target_group.this,
│   on main.tf line 54, in resource "aws_lb_target_group" "this":
│   54: resource "aws_lb_target_group" "this" {
│ 
╵
```

**Expected behavior**
It should create the Target Group without _stickiness_ configuration and by using the TCP protocol to forward the targets.

**Versions:**
 - Terraform: 1.0.0
 - provider registry.terraform.io/hashicorp/aws: v4.2.0
 - provider registry.terraform.io/hashicorp/local: v2.1.0

**Comment by cvegagimenez** [comment]
Hi, 

I have developed the fix, but I don't have privileges to push to a remote branch to do the Pull Request.

```
git push origin bugfix/5
ERROR: Permission to rhythmictech/terraform-aws-nlb-ecs-task.git denied to Gigigotrek.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

Can you provide those privileges?

**Comment by sblack4** [comment]
Hi,

First, thank you! 

Normally when contributing to an open-source project you create a fork of the project and push the changes to that fork. Then you can make the pull request to move those changes from your fork to the original project. It's kind of like your fork is the branch.

Don't let my explanation confuse you though, GitHub has an excellent guide (with pictures!) here https://docs.github.com/en/get-started/quickstart/contributing-to-projects
